### ISSUE TITLE
Error while fetching Conditional Access Policies

### ISSUE THREAD

**Issue by doron276** [microsoftgraph/msgraph-sdk-go#517]
github.com/microsoftgraph/msgraph-sdk-go (v0.55.0)

I'm using the following code to fetch Conditional Access Policies from Azure:
`result, err := client.Identity().ConditionalAccess().Policies().Get(ctx, nil)`
It works great.

The problem is when I create a policy with the parameters (users -> include -> select users and groups):
- b2bCollaborationGuest
- b2bCollaborationMember 
- b2bDirectConnectUser 
- otherExternalUser

I get the following error:

> Unknown ConditionalAccessGuestOrExternalUserTypes value: b2bCollaborationGuest,b2bCollaborationMember,b2bDirectConnectUser,otherExternalUser

Can you fix it?
Please advise!

**Comment by doron276** [comment]
The sdk does not know how to parse the response when several options (not just the values I mentioned above) are selected and fails the entire request. 
The microsof-sdk-go needs to be fixed so that it can receive some options in the answer.

**Comment by baywet** [comment]
Thanks using the Go SDK and for your patience on the matter.

@rkodev this should be considered a generation bug. The enum is flaggable (hence multiple values separate by a comma which currently makes deserialization fail).
The generator currently projects a single valued property https://github.com/microsoftgraph/msgraph-sdk-go/blob/3c04346d8f2b3dd59d9fdb234f2cf4b583819e23/models/conditional_access_guests_or_external_users.go#L66

Ideally we should keep a single valued property, but [during deserialization](https://github.com/microsoft/kiota-serialization-json-go/blob/4524db009e9188c008b8e7411b15b016803fc834/json_parse_node.go#L498) we'd "detect" the presence of a comma in the value, split, and compound a mask of all the values we parse.
Likewise, during serialization, we need to detect whether we have a single value or a mask, and serialize all the values separated by a comma when encountering a mask.

**Comment by doron276** [comment]
Thank you for the answer @baywet 

When do you expect to fix this bug?
This problem means that if there is one problematic policy, it causes an error for all the other policies so it is very critical.
Please advise!

**Comment by rkodev** [comment]
@doron276 This issue is currently in progress and should be fixed in next weeks release of the sdk

**Comment by rkodev** [comment]
Here is a sample code for the proposed generation changes with a mask

```go 
// file conditional_access_guests_or_external_users.go

package main

import (
	"errors"
	"strings"
)

type ConditionalAccessGuestOrExternalUserTypes int

const (
	NONE_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES ConditionalAccessGuestOrExternalUserTypes = iota
	INTERNALGUEST_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
	B2BCOLLABORATIONGUEST_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
	B2BCOLLABORATIONMEMBER_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
	B2BDIRECTCONNECTUSER_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
	OTHEREXTERNALUSER_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
	SERVICEPROVIDER_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
	UNKNOWNFUTUREVALUE_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
)

func (i ConditionalAccessGuestOrExternalUserTypes) String() string {
	var data []string
	for p := ConditionalAccessGuestOrExternalUserTypes(1); p <= UNKNOWNFUTUREVALUE_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES; p <<= 1 {
		if i&p == p {
			data = append(data, []string{"none", "internalGuest", "b2bCollaborationGuest", "b2bCollaborationMember", "b2bDirectConnectUser", "otherExternalUser", "serviceProvider", "unknownFutureValue"}[p])
		}
	}
	return strings.Join(data, ",")
}
func ParseConditionalAccessGuestOrExternalUserTypes(v string) (any, error) {
	// detect a command in the string and return enum as mask
	var result ConditionalAccessGuestOrExternalUserTypes
	values := strings.Split(v, ",")
	for _, str := range values {
		switch str {
		case "none":
			result |= NONE_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
		case "internalGuest":
			result |= INTERNALGUEST_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
		case "b2bCollaborationGuest":
			result |= B2BCOLLABORATIONGUEST_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
		case "b2bCollaborationMember":
			result |= B2BCOLLABORATIONMEMBER_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
		case "b2bDirectConnectUser":
			result |= B2BDIRECTCONNECTUSER_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
		case "otherExternalUser":
			result |= OTHEREXTERNALUSER_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
		case "serviceProvider":
			result |= SERVICEPROVIDER_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
		case "unknownFutureValue":
			result |= UNKNOWNFUTUREVALUE_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES
		default:
			return 0, errors.New("Unknown ConditionalAccessGuestOrExternalUserTypes value: " + v)
		}
	}
	return &result, nil
}


```

**Comment by akshaypatel96** [comment]
> @doron276 This issue is currently in progress and should be fixed in next weeks release of the sdk

Hi @rkodev , the fix in sdk for above issue will be applicable to msgraph-beta-sdk-go as well? When and  in which version of beta sdk we can expect new release with fix? 
Thanks!

**Comment by rkodev** [comment]
Hi @gmwiz, for the requested feature there is aPR that is targeting the next release of the SDK.

**Comment by baywet** [comment]
reopening since there are other requirements to implement before this is fixed

**Comment by doron276** [comment]
@baywet @rkodev 
It's been a few months and we still don't have a solution - very disappointing.
We need the solution as soon as possible!
When will the fix be published?

**Comment by baywet** [comment]
Hi everyone,
Sorry about the delay here. 

The reason why I re-opened this issue what because although the generator had been updated, we had not refreshed and published the generated code here.

But for over a month now, this ha been released.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/acc7e2ef0b7a1d6291811f122a0ae3083e867024/models/conditional_access_guest_or_external_user_types.go#L30

Can you get the latest version of the SDK, and confirm this is not an issue anymore please?

**Comment by baywet** [comment]
Thanks for confirming! Closing.
